"""add_product_libraries

Revision ID: bda0dbe57f2a
Revises: 34cdf003c3f7
Create Date: 2026-02-23 21:55:27.501142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bda0dbe57f2a'
down_revision: Union[str, Sequence[str], None] = '34cdf003c3f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_libraries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('naam', sa.String(length=255), nullable=False),
    sa.Column('verzekeraar', sa.String(length=255), nullable=True),
    sa.Column('versie', sa.String(length=100), nullable=True),
    sa.Column('beschrijving', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('aangemaakt_door', sa.String(length=255), nullable=False),
    sa.Column('aangemaakt_op', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bijgewerkt_op', sa.DateTime(timezone=True), nullable=False),
    sa.Column('build_progress', sa.Integer(), nullable=False),
    sa.Column('build_message', sa.Text(), nullable=True),
    sa.Column('section_count', sa.Integer(), nullable=False),
    sa.Column('clause_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('library_clauses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('library_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('tekst', sa.Text(), nullable=False),
    sa.Column('categorie', sa.String(length=255), nullable=True),
    sa.Column('embedding_vector', sa.LargeBinary(), nullable=True),
    sa.Column('embedding_model', sa.String(length=255), nullable=True),
    sa.Column('bron_bestand', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['library_id'], ['product_libraries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_library_clauses_library_id'), 'library_clauses', ['library_id'], unique=False)
    op.create_table('library_sections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('library_id', sa.String(length=36), nullable=False),
    sa.Column('artikel_nummer', sa.String(length=50), nullable=True),
    sa.Column('artikel_titel', sa.String(length=500), nullable=True),
    sa.Column('ruwe_tekst', sa.Text(), nullable=False),
    sa.Column('samenvatting', sa.Text(), nullable=True),
    sa.Column('sectie_type', sa.String(length=50), nullable=True),
    sa.Column('kernbegrippen', sa.Text(), nullable=True),
    sa.Column('embedding_vector', sa.LargeBinary(), nullable=True),
    sa.Column('embedding_model', sa.String(length=255), nullable=True),
    sa.Column('bron_bestand', sa.String(length=500), nullable=True),
    sa.Column('pagina_nummer', sa.Integer(), nullable=True),
    sa.Column('volgorde', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['product_libraries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_library_sections_library_id'), 'library_sections', ['library_id'], unique=False)
    op.create_table('library_synonym_overrides',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('library_id', sa.String(length=36), nullable=False),
    sa.Column('term', sa.String(length=255), nullable=False),
    sa.Column('synoniemen', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['product_libraries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('library_id', 'term', name='uq_library_synonym_term')
    )
    op.create_index(op.f('ix_library_synonym_overrides_library_id'), 'library_synonym_overrides', ['library_id'], unique=False)
    op.create_table('library_tfidf_indices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('library_id', sa.String(length=36), nullable=False),
    sa.Column('serialized_index', sa.LargeBinary(), nullable=False),
    sa.Column('vocabulary_size', sa.Integer(), nullable=False),
    sa.Column('document_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['product_libraries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('library_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('library_tfidf_indices')
    op.drop_index(op.f('ix_library_synonym_overrides_library_id'), table_name='library_synonym_overrides')
    op.drop_table('library_synonym_overrides')
    op.drop_index(op.f('ix_library_sections_library_id'), table_name='library_sections')
    op.drop_table('library_sections')
    op.drop_index(op.f('ix_library_clauses_library_id'), table_name='library_clauses')
    op.drop_table('library_clauses')
    op.drop_table('product_libraries')
    # ### end Alembic commands ###
